//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LoggerMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoggerMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Translations.LoggerMessages", typeof(LoggerMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating checksum for {0}.
        /// </summary>
        public static string CalculatingChecksum {
            get {
                return ResourceManager.GetString("CalculatingChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t set attributes on {0}: {1}.
        /// </summary>
        public static string CantSetAtributes {
            get {
                return ResourceManager.GetString("CantSetAtributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking checksum for {0}.
        /// </summary>
        public static string CheckingChecksum {
            get {
                return ResourceManager.GetString("CheckingChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking filesize for {0}.
        /// </summary>
        public static string CheckingFileSize {
            get {
                return ResourceManager.GetString("CheckingFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected with {0}.
        /// </summary>
        public static string ConnectedWith {
            get {
                return ResourceManager.GetString("ConnectedWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to {0}.
        /// </summary>
        public static string ConnectingTo {
            get {
                return ResourceManager.GetString("ConnectingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting {0}.
        /// </summary>
        public static string Deleting {
            get {
                return ResourceManager.GetString("Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloanding {0}.
        /// </summary>
        public static string Downloanding {
            get {
                return ResourceManager.GetString("Downloanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} is used by another process. Waitng {1} seconds for access. .
        /// </summary>
        public static string FileIsUsed {
            get {
                return ResourceManager.GetString("FileIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen on {0}.
        /// </summary>
        public static string ListenOn {
            get {
                return ResourceManager.GetString("ListenOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected directory ({0}) was not used as backup directory..
        /// </summary>
        public static string SelectedDirectoryIsNotBackupDirectory {
            get {
                return ResourceManager.GetString("SelectedDirectoryIsNotBackupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected directory ({0}) was used as backup directory but has been modified..
        /// </summary>
        public static string SelectedDirectoryWasModified {
            get {
                return ResourceManager.GetString("SelectedDirectoryWasModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending file size for {0}.
        /// </summary>
        public static string SendingFileSize {
            get {
                return ResourceManager.GetString("SendingFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading {0}.
        /// </summary>
        public static string Uploading {
            get {
                return ResourceManager.GetString("Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use this directory anyway, but any changes will be removed. Do you want use this directory? (type y/Y to use this directory).
        /// </summary>
        public static string UseModifiedDirectory {
            get {
                return ResourceManager.GetString("UseModifiedDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use this directory anyway, but some (maybe all of them) files and directories can be changed or removed. Do you want use this directory? (type y/Y to use this directory).
        /// </summary>
        public static string UseNewDirectory {
            get {
                return ResourceManager.GetString("UseNewDirectory", resourceCulture);
            }
        }
    }
}
